version: 0.2

env:
  variables:
    TERRAFORM_VERSION: 0.12.10
    TERRAFORM_SHA256: 2215208822f1a183fb57e24289de417c9b3157affbe8a5e520b768edbcb420b4
    TF_IN_AUTOMATION: 1

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && echo "${TERRAFORM_SHA256} terraform.zip" | sha256sum -c --quiet && unzip terraform.zip && mv terraform /usr/bin
  pre_build:
    commands:
      - cp -R $CODEBUILD_SRC_DIR /tmp/service-example
      - cd /tmp/service-example
  build:
    commands:
      - terraform apply -no-color -input=false plan
